### ISSUE TITLE
Rollup v0.4.0 for review

### ISSUE THREAD

**Issue by okuryu** [yui/yuidoc#280]
I'm planning to release v0.4.0 within a week. There're some new feature, bug fixes, enhancements, and dependencies updates. No breaking changes. All the changes as follows.
- New Features
  - [x] #158: Supports ES6 style rest parameters syntax for multiple parameters
  - [x] #253: Allow base URLs for external links (fixes #237)
  - [x] #261: Add `--no-sort` option (fixes #80)
- Bug Fixes
  - [x] #278: Fix fails to parse default parameters value that contains a space (fixes #268)
  - [x] #275: Fix a bug with a logo doesn't shows when use `preprocessor` feature
  - [x] #262: Fix a bug with parsing the optional parameters syntax
  - [x] #267: Fix a wrong link in the syntax document
  - [x] #269: Fix HTML syntax in the document
- Enhancements
  - [x] #276: Document for external base URLs
  - [x] #282: Test for `--no-sort` option
  - [x] #281: Add the help for `--no-sort` option
  - [x] #271: Revamp README
  - [x] #265: Drop Node.js 0.8 from Travis CI
- Dependencies Updates
  - [x] #277: Depend on `yui@^3.14.1`
  - [x] #274: Depend on `express@^4.10.1`
  - [x] #272: Depend on `minimatch^1.0.0`
  - [x] #266: Depend on `marked@^0.3.2`

@caridy @andrewnicols Any feedbacks welcome!
